vscode:
  extensions:
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - rebornix.ruby@0.25.3:EtnhuBkJKfh1e/xxxALcmA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
tasks:
  - command: >
        gem install rails &&
        bundle install &&
        yarn install --check-files &&
        rails server
